#!/bin/bash
# 2021 Martijn Atema <martijn@atema.one>

DOCUMENTATIE="\
Syntax: $0 [--achtergrond] [--test-achtergronden]
           [-o | --output output-naam] input-afbeelding

    --achtergrond
        Genereer een achtergrond voor een expeditie

    --test-achtergronden
        Genereer test-achtergronden in de ratios 5:2, 20:13 en 20:17 (met en zonder tekst)
        Impliceert --achtergrond
    
    -o, --output output-naam
        Basis voor de naam(en) van de gegenereerde afbeelding(en)

    input-afbeelding
        Bestandsnaam van de te gebruiken afbeelding"


print-error-en-stop() {
    >&2 printf "$1\n"
    exit 1
}


args=$(getopt -o o: -l achtergrond,test-achtergronden,output: -q -- "$@")

[ $? -ne 0 ] && print-error-en-stop "$DOCUMENTATIE"

eval "set -- $args"

output_basis="expeditie"
genereer_achtergrond=0
genereer_test_achtergronden=0

while true; do
    case "$1" in
        -o|--output)
            output_basis="$2"
            shift 2
            ;;
        --achtergrond)
            genereer_achtergrond=1
            shift
            ;;
        --test-achtergronden)
            genereer_achtergrond=1
            genereer_test_achtergronden=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            print-error-en-stop "$DOCUMENTATIE"
            ;;
    esac
done

[ $# -eq 0 ] && print-error-en-stop "$DOCUMENTATIE"
[ $# -ne 1 ] && print-error-en-stop "Specificeer niet meer dan één input afbeelding"
[ ! -f "$1" ] && print-error-en-stop "De gespecificeerde afbeelding bestaat niet"
command -v convert >/dev/null 2>&1 || print-error-en-stop "ImageMagick ('convert') is niet geïnstalleerd"


input_bestand="$1"
printf "Input: $input_bestand\n\n"

standaard_argumenten="-colorspace sRGB
                      -sampling-factor 4:2:0
                      -define jpeg:dct-method=float
                      -quality 80
                      -interlace Plane
                      -strip"


achtergrond_bestand="$output_basis-achtergrond.jpg"

if [ $genereer_achtergrond -eq 1 ]; then
    printf "%s\n    -> %s\n\n" \
           "Achtergrond wordt gegenereerd" \
           "$achtergrond_bestand"

    convert "$input_bestand" \
            $standaard_argumenten \
            -resize 1500 \
            "$achtergrond_bestand"
fi

if [ $genereer_test_achtergronden -eq 1 ]; then
    ratios=( 5x2 20x13 20x17 )

    for ratio in "${ratios[@]}"; do
        achtergrond_test_bestand="$output_basis-test-achtergrond-$ratio.jpg"

        printf "%s\n    -> %s\n\n" \
               "Test achtergrond ($ratio) wordt gegenereerd" \
               "$achtergrond_test_bestand"

        convert "$achtergrond_bestand" \
                -gravity center \
                -crop "${ratio//x/:}" \
                "$achtergrond_test_bestand"


        achtergrond_test_tekst_bestand="$output_basis-test-achtergrond-$ratio-tekst.jpg"

        printf "%s\n    -> %s\n\n" \
               "Test achtergrond met tekst ($ratio) wordt gegenereerd" \
               "$achtergrond_test_tekst_bestand"

        convert "$achtergrond_test_bestand" \
                -fill rgba\(0,0,0,.45\) \
                -draw "rectangle $(identify -format '0,%[fx:int(h*0.55)] %w,%h' $achtergrond_test_bestand)" \
                -gravity south \
                -font $(dirname "$0")/extras/OpenSans-Regular.ttf \
                -fill white \
                -pointsize 70 \
                -draw "text $(identify -format '0,%[fx:int(h*.225-20)]' $achtergrond_test_bestand) 'Expeditie Titel'" \
                -pointsize 40 \
                -draw "text $(identify -format '0,%[fx:int(h*.225-70)]' $achtergrond_test_bestand) 'Subtitel'" \
                "$achtergrond_test_tekst_bestand"
    done
fi
